
# file: ibert_ultrascale_gty_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT 7Series
##  /   /         Filename : example_ibert_ultrascale_gty_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT 7Series 
##**************************************************************************
##
##Eye scan 
##
set_property ES_EYE_SCAN_EN TRUE [get_cells QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel]
##
##
## TX/RX out clock and DMONITOR clock constraints
##
# GT X0Y16
create_clock -period 4.000 [get_pins {QUAD[0].u_q/CH[0].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[0].u_q/CH[0].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y17
create_clock -period 4.000 [get_pins {QUAD[0].u_q/CH[1].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[0].u_q/CH[1].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y18
create_clock -period 4.000 [get_pins {QUAD[0].u_q/CH[2].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[0].u_q/CH[2].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y19
create_clock -period 4.000 [get_pins {QUAD[0].u_q/CH[3].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[0].u_q/CH[3].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y32
create_clock -period 4.000 [get_pins {QUAD[1].u_q/CH[0].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[1].u_q/CH[0].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y33
create_clock -period 4.000 [get_pins {QUAD[1].u_q/CH[1].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[1].u_q/CH[1].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y34
create_clock -period 4.000 [get_pins {QUAD[1].u_q/CH[2].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[1].u_q/CH[2].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y35
create_clock -period 4.000 [get_pins {QUAD[1].u_q/CH[3].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[1].u_q/CH[3].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y36
create_clock -period 4.000 [get_pins {QUAD[2].u_q/CH[0].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[2].u_q/CH[0].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y37
create_clock -period 4.000 [get_pins {QUAD[2].u_q/CH[1].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[2].u_q/CH[1].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y38
create_clock -period 4.000 [get_pins {QUAD[2].u_q/CH[2].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[2].u_q/CH[2].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y39
create_clock -period 4.000 [get_pins {QUAD[2].u_q/CH[3].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[2].u_q/CH[3].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y40
create_clock -period 4.000 [get_pins {QUAD[3].u_q/CH[0].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[3].u_q/CH[0].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y41
create_clock -period 4.000 [get_pins {QUAD[3].u_q/CH[1].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[3].u_q/CH[1].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y42
create_clock -period 4.000 [get_pins {QUAD[3].u_q/CH[2].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[3].u_q/CH[2].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
# GT X0Y43
create_clock -period 4.000 [get_pins {QUAD[3].u_q/CH[3].u_ch/u_gtye4_channel/DMONITOROUTCLK}]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {QUAD[3].u_q/CH[3].u_ch/u_gtye4_channel/DMONITOROUTCLK}]]
##
## GTYE4 Channel and Common Loc constraints
##
set_property LOC GTYE4_CHANNEL_X0Y16 [get_cells QUAD[0].u_q/CH[0].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y17 [get_cells QUAD[0].u_q/CH[1].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y18 [get_cells QUAD[0].u_q/CH[2].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y19 [get_cells QUAD[0].u_q/CH[3].u_ch/u_gtye4_channel]
set_property LOC GTYE4_COMMON_X0Y4 [get_cells QUAD[0].u_q/u_common/u_gtye4_common]
set_property LOC GTYE4_CHANNEL_X0Y32 [get_cells QUAD[1].u_q/CH[0].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y33 [get_cells QUAD[1].u_q/CH[1].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y34 [get_cells QUAD[1].u_q/CH[2].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y35 [get_cells QUAD[1].u_q/CH[3].u_ch/u_gtye4_channel]
set_property LOC GTYE4_COMMON_X0Y8 [get_cells QUAD[1].u_q/u_common/u_gtye4_common]
set_property LOC GTYE4_CHANNEL_X0Y36 [get_cells QUAD[2].u_q/CH[0].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y37 [get_cells QUAD[2].u_q/CH[1].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y38 [get_cells QUAD[2].u_q/CH[2].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y39 [get_cells QUAD[2].u_q/CH[3].u_ch/u_gtye4_channel]
set_property LOC GTYE4_COMMON_X0Y9 [get_cells QUAD[2].u_q/u_common/u_gtye4_common]
set_property LOC GTYE4_CHANNEL_X0Y40 [get_cells QUAD[3].u_q/CH[0].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y41 [get_cells QUAD[3].u_q/CH[1].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y42 [get_cells QUAD[3].u_q/CH[2].u_ch/u_gtye4_channel]
set_property LOC GTYE4_CHANNEL_X0Y43 [get_cells QUAD[3].u_q/CH[3].u_ch/u_gtye4_channel]
set_property LOC GTYE4_COMMON_X0Y10 [get_cells QUAD[3].u_q/u_common/u_gtye4_common]
## Set case analysis on clock selection
set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/TXRATE[*]]
set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/RXRATE[*]]
		
		

set_case_analysis 1 [get_pins QUAD[0].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[0].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[0].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[2]]

set_case_analysis 0 [get_pins QUAD[0].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[0].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[0].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[2]]

set_case_analysis 1 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[2]]

	
set_case_analysis 1 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[0]]
set_case_analysis 1 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[1]]
		
	
set_case_analysis 1 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[0]]
set_case_analysis 1 [get_pins QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[1]]
		
		

set_case_analysis 1 [get_pins QUAD[1].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[1].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[1]]
set_case_analysis 1 [get_pins QUAD[1].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[2]]

set_case_analysis 0 [get_pins QUAD[1].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[1].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[1].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[2]]

set_case_analysis 1 [get_pins QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[2]]

	
set_case_analysis 1 [get_pins QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[0]]
set_case_analysis 1 [get_pins QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[1]]
		
	
set_case_analysis 1 [get_pins QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[0]]
set_case_analysis 1 [get_pins QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[1]]
		
		

set_case_analysis 1 [get_pins QUAD[2].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[2].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[2].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[2]]

set_case_analysis 0 [get_pins QUAD[2].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[2].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[2].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[2]]

set_case_analysis 1 [get_pins QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[2]]

	
set_case_analysis 1 [get_pins QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[0]]
set_case_analysis 1 [get_pins QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[1]]
		
	
set_case_analysis 1 [get_pins QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[0]]
set_case_analysis 1 [get_pins QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[1]]
		
		

set_case_analysis 1 [get_pins QUAD[3].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[3].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[3].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[2]]

set_case_analysis 0 [get_pins QUAD[3].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[3].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[3].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[2]]

set_case_analysis 1 [get_pins QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[0]]
set_case_analysis 0 [get_pins QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[2]]

	
set_case_analysis 1 [get_pins QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[0]]
set_case_analysis 1 [get_pins QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[1]]
		
	
set_case_analysis 1 [get_pins QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[0]]
set_case_analysis 1 [get_pins QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[1]]

set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/TXOUTCLKSEL[2]]
set_case_analysis 1 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/TXOUTCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/TXOUTCLKSEL[0]]

set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/RXOUTCLKSEL[2]]
set_case_analysis 1 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/RXOUTCLKSEL[1]]
set_case_analysis 0 [get_pins QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/RXOUTCLKSEL[0]]
