#================================================================================
#  Configure and add AXI slaves
#  Auto-generated by 
#================================================================================
#V_IO
{'axi_control': '${::AXI_MASTER_CTRL}', 'command': 'AXI_PL_DEV_CONNECT', 'addr': {'range': '4K', 'offset': 3017015296}}

#CM_V_INFO
{'axi_control': '${::AXI_MASTER_CTRL}', 'command': 'AXI_PL_DEV_CONNECT', 'addr': {'range': '4K', 'offset': 3017027584}}

#VIRTEX_IPBUS
{'axi_control': '${::AXI_MASTER_CTRL}', 'type': 'AXI4', 'command': 'AXI_PL_DEV_CONNECT', 'addr': {'range': '32M', 'offset': 3154116608}, 'data_width': '64'}

#V_C2C_PHY
{'axi_control': {'axi_rstn': '${::EXT_RESET}', 'axi_freq': 50000000, 'axi_clk': '${::EXT_CLK}', 'axi_interconnect': '${::AXI_INTERCONNECT_NAME}'}, 'remote_slave': 0, 'command': 'AXI_DEV_CONNECT', 'addr': {'range': '4K', 'offset': 3017031680}}

#VIRTEX_SYS_MGMT
{'enable_i2c_pins': 1, 'axi_control': '${::AXI_MASTER_CTRL}', 'remote_slave': 0, 'command': 'AXI_IP_SYS_MGMT', 'addr': {'range': '4K', 'offset': 3017023488}}

