AXI_CONTROL_SETS:
  AXI_MASTER_CTRL:
      axi_interconnect: "${::AXI_INTERCONNECT_NAME}"
      axi_clk: "${::AXI_MASTER_CLK}"
      axi_rstn: "${::AXI_MASTER_RSTN}"
      axi_freq: "${::AXI_MASTER_CLK_FREQ}"


AXI_SLAVES:
  V_IO:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xB3002000"
        range:  "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/CM_IO.xml"
    UHAL_BASE: 0x81000000
    HDL: 
      out_name: "IO"
      map_template: "axi_generic/template_map_withbram.vhd"
  VIRTEX_SYS_MGMT:
    TCL_CALL:
      command: AXI_IP_SYS_MGMT
      enable_i2c_pins: 1
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xB3001000"
        range: "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/VIRTEX_SYS_MGMT.xml"
    UHAL_BASE: 0x80000000
  
  V_CM_FW_INFO:
    TCL_CALL:
      command: AXI_PL_DEV_CONNECT 
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xB3003000"
        range:  "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/FW_INFO.xml"
    UHAL_BASE: 0x82000000
    HDL: 
      out_name: "CM_FW_INFO"
      map_template: "axi_generic/template_map.vhd"

  V_TCDS:
    TCL_CALL:
      command: AXI_PL_DEV_CONNECT 
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xB3004000"
        range:  "8K"
      remote_slave: "1"
    XML:
      - "address_table/modules/V_TCDS.xml"
      - "address_table/modules/DRP_USP_GTY.xml"
      - "address_table/modules/MGT_Status.xml"
      - "address_table/modules/MGT_DEBUG_USP.xml"
      - "address_table/modules/CM_C2C_CNT.xml"
    UHAL_BASE: 0x88000000
    HDL:
      out_name: "TCDS"
      map_template: "axi_generic/template_map.vhd"

  VIRTEX_IPBUS:
    TCL_CALL:
      command: AXI_PL_DEV_CONNECT 
      axi_control: "${::AXI_MASTER_CTRL}"
      type: "AXI4"
      addr:
        offset: "0xB2000000"
        range:  "16M"
      data_width: "64"
      remote_slave: "1"
    XML:
      - "address_table/modules/IPBUS.xml"
    UHAL_BASE: 0x85000000    

  V_C2C_INTF:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xB3010000"
        range:  "64K"
      remote_slave: "1"
    XML:
      - "address_table/modules/C2C_INTFS.xml"
      - "address_table/modules/C2C_INTF.xml"
      - "address_table/modules/DRP_USP_GTH.xml"
      - "address_table/modules/CM_C2C_Status.xml"
      - "address_table/modules/MGT_DEBUG_USP.xml"
      - "address_table/modules/CM_C2C_CNT.xml"
    UHAL_BASE: 0x86000000
    HDL: 
      out_name: "C2C_INTF"
      map_template: "axi_generic/template_map_withbram.vhd"
    SUB_SLAVES:
      CM1_PB_UART:
        TCL_CALL:
          command: "AXI_IP_UART"
          addr:
            offset: "0xB3008000"
            range:  "4K"
          irq_port: "V_C2CB/axi_c2c_s2m_intr_in"
          baud_rate: "115200"  
          axi_control: "${::AXI_MASTER_CTRL}"
          manual_load_dtsi: "1"
          remote_slave: "1"
          dt_data: "compatible = \"xlnx,axi-uartlite-2.0\", \"xlnx,xps-uartlite-1.00.a\";current-speed = <115200>;device_type = \"serial\";interrupt-names = \"interrupt\";interrupt-parent = <&IRQ0_INTR_CTRL>;interrupts = <4 0>;port-number = <101>;xlnx,baudrate = <0x1c200>;xlnx,data-bits = <0x8>;xlnx,odd-parity = <0x0>;xlnx,s-axi-aclk-freq-hz-d = \"49.9995\";xlnx,use-parity = <0x0>;
    "

CORES:
  onboardclk:
    TCL_CALL:
      command: BuildClockWizard
      in_clk_type: Differential_clock_capable_pin
      in_clk_freq_MHZ: 200
      out_clks:
        1: 200
        2: 50

  localTCDS_MGT:
    TCL_CALL:
      command: BuildMGTCores
      GT_TYPE: GTY
      freerun_frequency: 50
      clocking:
        TX:
          LINE_RATE: 10.260224
          PLL_TYPE: QPLL1
          REFCLK_FREQUENCY: 320.632
          OUTCLK_SOURCE: TXOUTCLKPMA
        RX:
          LINE_RATE: 10.260224
          PLL_TYPE: QPLL1
          REFCLK_FREQUENCY: 320.632
          OUTCLK_SOURCE: RXOUTCLKPMA 
      protocol:
        TX:
          DATA_ENCODING: 8B10B
          INT_DATA_WIDTH: 40
        RX:
          DATA_DECODING: 8B10B
          COMMA_PRESET: K28.5
          COMMA_P_ENABLE: true    
          COMMA_M_ENABLE: true    
          COMMA_MASK: 1111111111  
      core:
        LOCATE_TX_USER_CLOCKING: CORE
        LOCATE_RX_USER_CLOCKING: CORE
        LOCATE_COMMON: CORE
      links:
        X1Y3:
          RX: clk0+1
          TX: clk0+1
      optional: "drpaddr_in drpclk_in drpdi_in drpen_in drpwe_in eyescanreset_in eyescantrigger_in pcsrsvdin_in rxbufreset_in rxcdrhold_in rxdfelpmreset_in rxlpmen_in rxpcsreset_in rxpmareset_in rxprbscntreset_in rxprbssel_in rxrate_in txdiffctrl_in txinhibit_in txpcsreset_in txpmareset_in txpolarity_in txpostcursor_in txprbsforceerr_in txprbssel_in txprecursor_in cplllock_out dmonitorout_out drpdo_out drprdy_out eyescandataerror_out rxprbserr_out rxresetdone_out txbufstatus_out txresetdone_out"

