AXI_CONTROL_SETS:
  AXI_MASTER_CTRL:
      axi_interconnect: "${::AXI_INTERCONNECT_NAME}"
      axi_clk: "${::AXI_MASTER_CLK}"
      axi_rstn: "${::AXI_MASTER_RSTN}"
      axi_freq: "${::AXI_MASTER_CLK_FREQ}"


AXI_SLAVES:
  V_C2C_PHY:
    TCL_CALL: 
      command: AXI_DEV_CONNECT
      axi_control:
        axi_interconnect: ${::AXI_INTERCONNECT_NAME}
        axi_clk: ${::EXT_CLK} 
        axi_rstn: ${::EXT_RESET} 
        axi_freq: 50000000 
      addr:
        offset: 0xB3004000
        range: 4K
      remote_slave: "1"
    XML:
      - "address_table/modules/DRP_USP_GTY.xml"
    UHAL_BASE: 0xC6000000

  VIRTEX_SYS_MGMT:
    TCL_CALL: 
      command: AXI_IP_SYS_MGMT
      enable_i2c_pins: 1
      axi_control: ${::AXI_MASTER_CTRL}
      addr:
        offset: 0xB3002000
        range: 4K
      remote_slave: "1"
    XML:
      - "address_table/modules/VIRTEX_SYS_MGMT.xml"
    UHAL_BASE: 0xC0000000
  
  V_IO:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: ${::AXI_MASTER_CTRL}
      addr:
        offset: 0xB3001000 
        range: 4K
      remote_slave: "1"
    XML:
      - "address_table/modules/CM_IO.xml"
      - "address_table/modules/CM_C2C_DEBUG_USP.xml"
      - "address_table/modules/CM_C2C_Status.xml"
    UHAL_BASE: 0xC1000000
    HDL: 
      out_dir: "src/CM_IO"    
      map_template: "axi_generic/template_map.vhd"
  
  CM_V_INFO:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: ${::AXI_MASTER_CTRL}
      addr:
        offset: 0xB3003000
        range: 4K
      remote_slave: "1"
    XML:
      - "address_table/modules/FW_INFO.xml"
    UHAL_BASE: 0xC2000000
    HDL: 
      out_dir: "src/CM_FW_info"
      map_template: "axi_generic/template_map.vhd"
                  
  VIRTEX_IPBUS:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: ${::AXI_MASTER_CTRL}
      addr:
        offset: 0xB2000000
        range: 16M
      type: AXI4
      data_width: "64"
      remote_slave: "1"
    XML:
      - "address_table/modules/IPBUS.xml"
    UHAL_BASE: 0xC5000000    
  
