#================================================================================
#  Configure and add AXI slaves
#  Auto-generated by 
#================================================================================
#KINTEX_SYS_MGMT
{'enable_i2c_pins': 0, 'axi_control': '${::AXI_MASTER_CTRL}', 'remote_slave': '1', 'command': 'AXI_IP_SYS_MGMT', 'addr': {'range': '4K', 'offset': '0x83c42000'}}

#KINTEX_IPBUS
{'axi_control': '${::AXI_MASTER_CTRL}', 'command': 'AXI_PL_DEV_CONNECT', 'addr': {'range': '32M', 'offset': '0x8a000000'}, 'remote_slave': '1', 'type': 'AXI4', 'data_width': '64'}

#CM_K_INFO
{'axi_control': '${::AXI_MASTER_CTRL}', 'remote_slave': '1', 'command': 'AXI_PL_DEV_CONNECT', 'addr': {'range': '4K', 'offset': '0x83c43000'}}

#K_C2C_PHY
{'axi_control': {'axi_rstn': '${::EXT_RESET}', 'axi_freq': '${::EXT_CLK_FREQ}', 'axi_clk': '${::EXT_CLK}', 'axi_interconnect': '${::AXI_INTERCONNECT_NAME}'}, 'remote_slave': '1', 'command': 'AXI_DEV_CONNECT', 'addr': {'range': '4K', 'offset': '0xB3c44000'}}

#K_IO
{'axi_control': '${::AXI_MASTER_CTRL}', 'remote_slave': '1', 'command': 'AXI_PL_DEV_CONNECT', 'addr': {'range': '4K', 'offset': '0x83c40000'}}

