
# file: ibert_ultrascale_gty_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gty_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##

set_property C_CLK_INPUT_FREQ_HZ 50000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets AXI_CLK]

##
##gtrefclk lock constraints
##
## set_property PACKAGE_PIN AY39 [get_ports gty_refclk0p_i[0]]
## set_property PACKAGE_PIN AY40 [get_ports gty_refclk0n_i[0]]
## set_property PACKAGE_PIN AW41 [get_ports gty_refclk1p_i[0]]
## set_property PACKAGE_PIN AW42 [get_ports gty_refclk1n_i[0]]
## set_property PACKAGE_PIN AT39 [get_ports gty_refclk0p_i[1]]
## set_property PACKAGE_PIN AT40 [get_ports gty_refclk0n_i[1]]
## set_property PACKAGE_PIN AR41 [get_ports gty_refclk1p_i[1]]
## set_property PACKAGE_PIN AR42 [get_ports gty_refclk1n_i[1]]
## set_property PACKAGE_PIN AM39 [get_ports gty_refclk0p_i[2]]
## set_property PACKAGE_PIN AM40 [get_ports gty_refclk0n_i[2]]
## set_property PACKAGE_PIN AL41 [get_ports gty_refclk1p_i[2]]
## set_property PACKAGE_PIN AL42 [get_ports gty_refclk1n_i[2]]
## set_property PACKAGE_PIN AA41 [get_ports gty_refclk0p_i[3]]
## set_property PACKAGE_PIN AA42 [get_ports gty_refclk0n_i[3]]
## set_property PACKAGE_PIN Y39 [get_ports gty_refclk1p_i[3]]
## set_property PACKAGE_PIN Y40 [get_ports gty_refclk1n_i[3]]
## set_property PACKAGE_PIN W41 [get_ports gty_refclk0p_i[4]]
## set_property PACKAGE_PIN W42 [get_ports gty_refclk0n_i[4]]
## set_property PACKAGE_PIN V39 [get_ports gty_refclk1p_i[4]]
## set_property PACKAGE_PIN V40 [get_ports gty_refclk1n_i[4]]
## set_property PACKAGE_PIN N41 [get_ports gty_refclk0p_i[5]]
## set_property PACKAGE_PIN N42 [get_ports gty_refclk0n_i[5]]
## set_property PACKAGE_PIN M39 [get_ports gty_refclk1p_i[5]]
## set_property PACKAGE_PIN M40 [get_ports gty_refclk1n_i[5]]
##
## Refclk constraints
##
#create_clock -name gtrefclk0_2 -period 3.104 [get_ports p_lf_r0_ad]
create_clock -name gtrefclk0_2 -period 3.1030303 [get_ports p_lf_r0_ad]
set_clock_groups -group [get_clocks gtrefclk0_2 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_4 -period 3.1030303 [get_ports p_lf_r0_af]
set_clock_groups -group [get_clocks gtrefclk0_4 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_6 -period 3.1030303 [get_ports p_lf_r0_r]
set_clock_groups -group [get_clocks gtrefclk0_6 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_9 -period 3.1030303 [get_ports p_lf_r0_u]
set_clock_groups -group [get_clocks gtrefclk0_9 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_10 -period 3.1030303 [get_ports p_lf_r0_v]
set_clock_groups -group [get_clocks gtrefclk0_10 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_13 -period 3.1030303 [get_ports p_lf_r0_y]
set_clock_groups -group [get_clocks gtrefclk0_13 -include_generated_clocks] -asynchronous

