

#################################################################################
# Clean
#################################################################################
clean_prebuild:
	@echo "Cleaning up prebuild autogenerated files"
	@rm -f $(ADDSLAVE_TCL_PATH)/AddSlaves*.tcl 
	@rm -f $(ADDRESS_TABLE_CREATION_PATH)/slaves*.yaml
	@rm -rf $(ADDRESS_TABLE_CREATION_PATH)/address_table/*
	@rm -f $(SLAVE_DTSI_PATH)/slaves*.yaml

#################################################################################
# generate prebuilds for FPGA builds in config
#################################################################################
define PREBUILD_template =
 prebuild_$(1):  $(SLAVE_DTSI_PATH)/slaves_$(1).yaml $(ADDRESS_TABLE_CREATION_PATH)/slaves_$(1).yaml 


endef
PREBUILDS=$(addprefix,prebuild_,$(CONFIGS))

#################################################################################
# prebuild 
#################################################################################

ifdef CACTUS_ROOT
	USE_SIMPLE_PARSER=-u False
	CACTUS_LD_PATH:=$(CACTUS_ROOT)"/lib/"
else
	USE_SIMPLE_PARSER=-u True
endif

$(SLAVE_DTSI_PATH)/slaves_%.yaml $(ADDRESS_TABLE_CREATION_PATH)/slaves_%.yaml : $(SLAVE_DEF_FILE_BASE)/%/slaves.yaml
	@mkdir -p $(ADDRESS_TABLE_CREATION_PATH)
	@mkdir -p $(SLAVE_DTSI_PATH)
	LD_LIBRARY_PATH=$(CACTUS_LD_PATH) ./scripts/preBuild.py \
			                     -s $^ \
				             -a $(subst $(SLAVE_DTSI_PATH),$(ADDRESS_TABLE_CREATION_PATH),$@) \
				             -d $(subst $(ADDRESS_TABLE_CREATION_PATH), $(SLAVE_DTSI_PATH),$@) \
                                             $(USE_SIMPLE_PARSER)



$(foreach prebuild,$(CONFIGS),$(eval $(call PREBUILD_template,$(prebuild))))
