CACTUS_ROOT:="/opt/cactus"
CACTUS_LD_PATH:=$(CACTUS_ROOT)"/lib/"

#################################################################################
# Clean
#################################################################################
clean_prebuild:
	@echo "Cleaning up prebuild autogenerated files"
	@rm -f $(ADDSLAVE_TCL_PATH)/AddSlaves.tcl 
	@rm -f $(ADDRESS_TABLE_CREATION_PATH)/slaves.yaml
	@rm -rf $(ADDRESS_TABLE_CREATION_PATH)/address_table/*
	@rm -f $(SLAVE_DTSI_PATH)/slaves.yaml

#################################################################################
# prebuild 
#################################################################################
prebuild: $(SLAVE_DEF_FILE)
	LD_LIBRARY_PATH=$(CACTUS_LD_PATH) ./scripts/preBuild.py \
			                     -s $(SLAVE_DEF_FILE) \
				             -t $(ADDSLAVE_TCL_PATH) \
				             -a $(ADDRESS_TABLE_CREATION_PATH) \
				             -d $(SLAVE_DTSI_PATH)

$(ADDSLAVE_TCL_PATH)/AddSlaves.tcl $(ADDRESS_TABLE_CREATION_PATH)/slaves.yaml $(SLAVE_DTSI_PATH)/slaves.yaml: prebuild

