AXI_CONTROL_SETS:
  AXI_MASTER_CTRL:
      axi_interconnect: "${::AXI_INTERCONNECT_NAME}"
      axi_clk: "${::AXI_MASTER_CLK}"
      axi_rstn: "${::AXI_MASTER_RSTN}"
      axi_freq: "${::AXI_MASTER_CLK_FREQ}"

AXI_SLAVES:
  K_IO:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x81002000"
        range:  "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/CM_IO.xml"
      - "address_table/modules/CM_C2C_DEBUG_USP.xml"
      - "address_table/modules/CM_C2C_Status.xml"
    UHAL_BASE: 0x81000000
    HDL: 
      out_dir: "configs/Cornell_rev1_p1_KU15p-2-SM_7s/autogen/CM_IO"    
      map_template: "axi_generic/template_map.vhd"
  KINTEX_SYS_MGMT:
    TCL_CALL:
      command: AXI_IP_SYS_MGMT
      enable_i2c_pins: 1
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x81001000"
        range: "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/KINTEX_SYS_MGMT.xml"
    UHAL_BASE: 0x80000000  
  CM_K_INFO:
    TCL_CALL:
      command: AXI_PL_DEV_CONNECT 
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x81003000"
        range:  "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/FW_INFO.xml"
    UHAL_BASE: 0x82000000
    HDL: 
      out_dir: "configs/Cornell_rev1_p1_KU15p-2-SM_7s/autogen/CM_FW_info"
      map_template: "axi_generic/template_map.vhd"
  K_C2C_INTF:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x81004000"
        range:  "8K"
      remote_slave: "1"
    XML:
      - "address_table/modules/C2C_INTFS.xml"
      - "address_table/modules/C2C_INTF.xml"
      - "address_table/modules/DRP_USP_GTH.xml"
      - "address_table/modules/CM_C2C_Status.xml"
      - "address_table/modules/CM_C2C_DEBUG_USP.xml"
      - "address_table/modules/CM_C2C_CNT.xml"
    UHAL_BASE: 0x86000000
    HDL: 
      out_dir: "configs/Cornell_rev1_p1_KU15p-2-SM_7s/autogen/C2C_INTF"    
      map_template: "axi_generic/template_map_withbram.vhd"
             
  KINTEX_IPBUS:
    TCL_CALL:
      command: AXI_PL_DEV_CONNECT 
      axi_control: "${::AXI_MASTER_CTRL}"
      type: "AXI4"
      addr:
        offset: "0x80000000"
        range:  "16M"
      data_width: "64"
      remote_slave: "1"
    XML:
      - "address_table/modules/IPBUS.xml"
    UHAL_BASE: 0x85000000    
