AXI_SLAVES:
  BASE:
    INCLUDE_FILE: ${::apollo_root_path}/src/CM_yaml/Cornell_base.yaml
    SUB_SLAVES:
      C2C:
        INCLUDE_FILE: ${::apollo_root_path}/src/CM_C2C/Cornell_rev2_p1_C2C.yaml
      F1_IPBUS:
        TCL_CALL:
          command: AXI_PL_DEV_CONNECT 
          axi_control: "${::AXI_ENDPOINT_CTRL}"
          type: "AXI4"
          addr:
            offset: "0xB0000000"
            range:  "16M"
          data_width: "64"
          remote_slave: "1"
        XML: "address_table/modules/IPBUS.xml"
        UHAL_BASE: 0x85000000    
      F1_IO:
        TCL_CALL: 
          command: AXI_PL_DEV_CONNECT
          axi_control: "${::AXI_ENDPOINT_CTRL}"
          addr:
            offset: "0xB1002000"
            range: "4K"
          remote_slave: "1"
        XML: "address_table/modules/CM_IO.xml"
        UHAL_BASE: 0x81000000
        HDL: 
          out_name: "IO"
          map_template: "axi_generic/template_map_withbram.vhd"
      F1_SYS_MGMT:
        TCL_CALL:
          command: AXI_IP_SYS_MGMT
          enable_i2c_pins: 1
          axi_control: "${::AXI_ENDPOINT_CTRL}"
          addr:
            offset: "0xB1001000"
            range: "4K"
          remote_slave: "1"
        XML: "address_table/modules/KINTEX_SYS_MGMT.xml"
        UHAL_BASE: 0x80000000
      F1_CM_FW_INFO:
        TCL_CALL:
          command: AXI_PL_DEV_CONNECT 
          axi_control: "${::AXI_ENDPOINT_CTRL}"
          addr:
            offset: "0xB1003000"
            range: "4K"
          remote_slave: "1"
        XML: "address_table/modules/FW_INFO.xml"
        UHAL_BASE: 0x82000000
        HDL: 
          out_name: "CM_FW_INFO"
          map_template: "axi_generic/template_map.vhd"


CORES:
  onboardclk:
    TCL_CALL:
      command: IP_CORE_ClockWizard
      in_clk_type: Differential_clock_capable_pin
      in_clk_freq_MHZ: 200
      out_clks:
        1: 200
        2: 50
