set_property SRC_FILE_INFO {cfile:/home/dan/work/CMS/APOLLO/CU_PCB_6089-103/dan/bd/c2cSlave/ip/c2cSlave_C2CLink_0_1/c2cSlave_C2CLink_0.xdc rfile:../../bd/c2cSlave/ip/c2cSlave_C2CLink_0_1/c2cSlave_C2CLink_0.xdc id:1 order:EARLY scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/dan/work/CMS/APOLLO/CU_PCB_6089-103/dan/bd/c2cSlave/ip/c2cSlave_C2CLink_phy_0_1/ip_0/synth/c2cSlave_C2CLink_phy_0_gt.xdc rfile:../../bd/c2cSlave/ip/c2cSlave_C2CLink_phy_0_1/ip_0/synth/c2cSlave_C2CLink_phy_0_gt.xdc id:2 order:EARLY scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink_phy/inst/c2cSlave_C2CLink_phy_0_core_i/c2cSlave_C2CLink_phy_0_wrapper_i/c2cSlave_C2CLink_phy_0_multi_gt_i/c2cSlave_C2CLink_phy_0_gt_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/dan/work/CMS/APOLLO/CU_PCB_6089-103/dan/src/top_pins.xdc rfile:../../src/top_pins.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/home/dan/work/CMS/APOLLO/CU_PCB_6089-103/dan/src/top_timing.xdc rfile:../../src/top_timing.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:/home/dan/work/CMS/APOLLO/CU_PCB_6089-103/dan/bd/c2cSlave/ip/c2cSlave_C2CLink_0_1/c2cSlave_C2CLink_0_clocks.xdc rfile:../../bd/c2cSlave/ip/c2cSlave_C2CLink_0_1/c2cSlave_C2CLink_0_clocks.xdc id:5 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:6 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:7 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:8 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:9 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:10 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:11 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:12 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:13 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:14 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:15 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:16 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:17 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:18 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:19 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:20 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:21 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:22 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:23 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:24 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:25 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:26 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:27 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:28 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:29 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:30 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:31 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:32 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../../../opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:33 order:LATE scoped_inst:c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins -filter {REF_PIN_NAME=~C} -of_objects [get_cells -hierarchical -filter {NAME=~*slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/calib_done_flop_reg}]] -to [get_pins -filter {REF_PIN_NAME=~D} -of_objects [get_cells -hierarchical -filter {NAME=~*slave_fpga_gen.axi_chip2chip_slave_phy_inst/axi_chip2chip_phy_init_inst/axi_chip2chip_sync_cell_inst/sync_flop_0_reg*[*]}]] -datapath_only 10.000
set_property src_info {type:SCOPED_XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {c2csslave_wrapper_1/c2cSlave_i/C2CLink_phy/inst/c2cSlave_C2CLink_phy_0_core_i/c2cSlave_C2CLink_phy_0_wrapper_i/c2cSlave_C2CLink_phy_0_multi_gt_i/c2cSlave_C2CLink_phy_0_gt_i/inst/gen_gtwizard_gthe4_top.c2cSlave_C2CLink_phy_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[0].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {c2csslave_wrapper_1/c2cSlave_i/C2CLink_phy/inst/c2cSlave_C2CLink_phy_0_core_i/c2cSlave_C2CLink_phy_0_wrapper_i/c2cSlave_C2CLink_phy_0_multi_gt_i/c2cSlave_C2CLink_phy_0_gt_i/inst/gen_gtwizard_gthe4_top.c2cSlave_C2CLink_phy_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[0].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {c2csslave_wrapper_1/c2cSlave_i/C2CLink_phy/inst/c2cSlave_C2CLink_phy_0_core_i/c2cSlave_C2CLink_phy_0_wrapper_i/c2cSlave_C2CLink_phy_0_multi_gt_i/c2cSlave_C2CLink_phy_0_gt_i/inst/gen_gtwizard_gthe4_top.c2cSlave_C2CLink_phy_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[0].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/TXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {c2csslave_wrapper_1/c2cSlave_i/C2CLink_phy/inst/c2cSlave_C2CLink_phy_0_core_i/c2cSlave_C2CLink_phy_0_wrapper_i/c2cSlave_C2CLink_phy_0_multi_gt_i/c2cSlave_C2CLink_phy_0_gt_i/inst/gen_gtwizard_gthe4_top.c2cSlave_C2CLink_phy_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[0].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/RXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {c2csslave_wrapper_1/c2cSlave_i/C2CLink_phy/inst/c2cSlave_C2CLink_phy_0_core_i/c2cSlave_C2CLink_phy_0_wrapper_i/c2cSlave_C2CLink_phy_0_multi_gt_i/c2cSlave_C2CLink_phy_0_gt_i/inst/gen_gtwizard_gthe4_top.c2cSlave_C2CLink_phy_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[0].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/RXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {c2csslave_wrapper_1/c2cSlave_i/C2CLink_phy/inst/c2cSlave_C2CLink_phy_0_core_i/c2cSlave_C2CLink_phy_0_wrapper_i/c2cSlave_C2CLink_phy_0_multi_gt_i/c2cSlave_C2CLink_phy_0_gt_i/inst/gen_gtwizard_gthe4_top.c2cSlave_C2CLink_phy_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_channel_container[0].gen_enabled_channel.gthe4_channel_wrapper_inst/channel_inst/gthe4_channel_gen.gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST/RXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE4_CHANNEL_X0Y0 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[0].*gen_gthe4_channel_inst[0].GTHE4_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {c2csslave_wrapper_1/c2cSlave_i/C2CLink_phy/inst/c2cSlave_C2CLink_phy_0_core_i/c2cSlave_C2CLink_phy_0_wrapper_i/c2cSlave_C2CLink_phy_0_multi_gt_i/c2cSlave_C2CLink_phy_0_gt_i/inst/gen_gtwizard_gthe4_top.c2cSlave_C2CLink_phy_0_gt_gtwizard_gthe4_inst/gen_gtwizard_gthe4.gen_pwrgood_delay_inst[0].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G21 [get_ports  n_clk_200 ]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G22 [get_ports  p_clk_200 ]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports *_atca_ttc_in]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM_ADV TERM_100 [get_ports *_atca_ttc_in]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AY1 [get_ports  n_atca_ttc_in ]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AY2 [get_ports  p_atca_ttc_in ]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports *_atca_tts_out]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AU7 [get_ports  n_atca_tts_out ]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AU8 [get_ports  p_atca_tts_out ]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports *_amc13_clk_40]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports *_amc13_clk_40]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM_ADV TERM_100 [get_ports *_amc13_clk_40]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J23 [get_ports  n_amc13_clk_40 ]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K23 [get_ports  p_amc13_clk_40 ]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports *_amc13_cdr_data]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM TRUE [get_ports *_amc13_cdr_data]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property DIFF_TERM_ADV TERM_100 [get_ports *_amc13_cdr_data]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G24 [get_ports  n_amc13_cdr_data ]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H24 [get_ports  p_amc13_cdr_data ]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports *_amc13_tts_out]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F23 [get_ports  n_amc13_tts_out ]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G23 [get_ports  p_amc13_tts_out ]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AL11 [get_ports  n_util_clk_chan0 ]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AL12 [get_ports  p_util_clk_chan0 ]
set_property src_info {type:XDC file:3 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AG11 [get_ports  n_clk0_chan0 ]
set_property src_info {type:XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AG12 [get_ports  p_clk0_chan0 ]
set_property src_info {type:XDC file:3 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF9  [get_ports  n_clk1_chan0 ]
set_property src_info {type:XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF10 [get_ports  p_clk1_chan0 ]
set_property src_info {type:XDC file:3 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AA11 [get_ports  n_clk0_chan1 ]
set_property src_info {type:XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AA12 [get_ports  p_clk0_chan1 ]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y9   [get_ports  n_clk1_chan1 ]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y10  [get_ports  p_clk1_chan1 ]
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  R11  [get_ports  n_clk0_chan2 ]
set_property src_info {type:XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  R12  [get_ports  p_clk0_chan2 ]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P9   [get_ports  n_clk1_chan2 ]
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P10  [get_ports  p_clk1_chan2 ]
set_property src_info {type:XDC file:3 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AD33 [get_ports  n_clk0_chan4 ]
set_property src_info {type:XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AD32 [get_ports  p_clk0_chan4 ]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AC31 [get_ports  n_clk1_chan4 ]
set_property src_info {type:XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AC30 [get_ports  p_clk1_chan4 ]
set_property src_info {type:XDC file:3 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V33  [get_ports  n_clk0_chan5 ]
set_property src_info {type:XDC file:3 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V32  [get_ports  p_clk0_chan5 ]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U31  [get_ports  n_clk1_chan5 ]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U30  [get_ports  p_clk1_chan5 ]
set_property src_info {type:XDC file:3 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P33  [get_ports  n_clk0_chan6 ]
set_property src_info {type:XDC file:3 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P32  [get_ports  p_clk0_chan6 ]
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N31  [get_ports  n_clk1_chan6 ]
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N30  [get_ports  p_clk1_chan6 ]
set_property src_info {type:XDC file:3 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M33  [get_ports  n_util_clk_chan1 ]
set_property src_info {type:XDC file:3 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M32  [get_ports  p_util_clk_chan1 ]
set_property src_info {type:XDC file:3 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  D42  [get_ports  {n_mgt_v2k[0]} ]
set_property src_info {type:XDC file:3 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  D41  [get_ports  {p_mgt_v2k[0]} ]
set_property src_info {type:XDC file:3 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  C40  [get_ports  {n_mgt_v2k[1]} ]
set_property src_info {type:XDC file:3 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  C39  [get_ports  {p_mgt_v2k[1]} ]
set_property src_info {type:XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  B42  [get_ports  {n_mgt_v2k[2]} ]
set_property src_info {type:XDC file:3 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  B41  [get_ports  {p_mgt_v2k[2]} ]
set_property src_info {type:XDC file:3 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K37  [get_ports  {n_mgt_k2v[0]} ]
set_property src_info {type:XDC file:3 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K36  [get_ports  {p_mgt_k2v[0]} ]
set_property src_info {type:XDC file:3 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K33  [get_ports  {n_mgt_k2v[1]} ]
set_property src_info {type:XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K32  [get_ports  {p_mgt_k2v[1]} ]
set_property src_info {type:XDC file:3 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J35  [get_ports  {n_mgt_k2v[2]} ]
set_property src_info {type:XDC file:3 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J34  [get_ports  {p_mgt_k2v[2]} ]
set_property src_info {type:XDC file:3 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  BA3  [get_ports  {n_mgt_z2k[1]} ]
set_property src_info {type:XDC file:3 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  BA4  [get_ports  {p_mgt_z2k[1]} ]
set_property src_info {type:XDC file:3 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  BB5  [get_ports  {n_mgt_z2k[2]} ]
set_property src_info {type:XDC file:3 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  BB6  [get_ports  {p_mgt_z2k[2]} ]
set_property src_info {type:XDC file:3 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AV9  [get_ports  {n_mgt_k2z[1]} ]
set_property src_info {type:XDC file:3 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AV10 [get_ports  {p_mgt_k2z[1]} ]
set_property src_info {type:XDC file:3 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AW7  [get_ports  {n_mgt_k2z[2]} ]
set_property src_info {type:XDC file:3 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AW8  [get_ports  {p_mgt_k2z[2]} ]
set_property src_info {type:XDC file:3 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports dip_sw*]
set_property src_info {type:XDC file:3 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AV32 [get_ports  {dip_sw[2]} ]
set_property src_info {type:XDC file:3 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AU32 [get_ports  {dip_sw[3]} ]
set_property src_info {type:XDC file:3 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  BA29 [get_ports  led_blue ]
set_property src_info {type:XDC file:3 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AY28 [get_ports  led_green ]
set_property src_info {type:XDC file:3 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AW28 [get_ports  led_red ]
set_property src_info {type:XDC file:3 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports *_tm4c]
set_property src_info {type:XDC file:3 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  D22 [get_ports  from_tm4c ]
set_property src_info {type:XDC file:3 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H22 [get_ports  to_tm4c ]
set_property src_info {type:XDC file:3 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports *_kv_spare*]
set_property src_info {type:XDC file:3 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  B22  [get_ports  {n_kv_spare[0]} ]
set_property src_info {type:XDC file:3 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  A23  [get_ports  {n_kv_spare[1]} ]
set_property src_info {type:XDC file:3 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  B24  [get_ports  {n_kv_spare[2]} ]
set_property src_info {type:XDC file:3 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  C21  [get_ports  {n_kv_spare[3]} ]
set_property src_info {type:XDC file:3 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  D23  [get_ports  {n_kv_spare[4]} ]
set_property src_info {type:XDC file:3 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  E21  [get_ports  {n_kv_spare[5]} ]
set_property src_info {type:XDC file:3 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J22  [get_ports  {n_kv_spare[6]} ]
set_property src_info {type:XDC file:3 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F20  [get_ports  {n_kv_spare[7]} ]
set_property src_info {type:XDC file:3 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  E23  [get_ports  {n_kv_spare[8]} ]
set_property src_info {type:XDC file:3 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H20  [get_ports  {n_kv_spare[9]} ]
set_property src_info {type:XDC file:3 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L23  [get_ports  {n_kv_spare[10]} ]
set_property src_info {type:XDC file:3 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J20  [get_ports  {n_kv_spare[11]} ]
set_property src_info {type:XDC file:3 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K21  [get_ports  {n_kv_spare[12]} ]
set_property src_info {type:XDC file:3 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  B23  [get_ports  {p_kv_spare[0]} ]
set_property src_info {type:XDC file:3 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  A24  [get_ports  {p_kv_spare[1]} ]
set_property src_info {type:XDC file:3 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  C24  [get_ports  {p_kv_spare[2]} ]
set_property src_info {type:XDC file:3 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  C22  [get_ports  {p_kv_spare[3]} ]
set_property src_info {type:XDC file:3 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  D24  [get_ports  {p_kv_spare[4]} ]
set_property src_info {type:XDC file:3 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  E22  [get_ports  {p_kv_spare[5]} ]
set_property src_info {type:XDC file:3 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K22  [get_ports  {p_kv_spare[6]} ]
set_property src_info {type:XDC file:3 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F21  [get_ports  {p_kv_spare[7]} ]
set_property src_info {type:XDC file:3 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F24  [get_ports  {p_kv_spare[8]} ]
set_property src_info {type:XDC file:3 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H21  [get_ports  {p_kv_spare[9]} ]
set_property src_info {type:XDC file:3 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L24  [get_ports  {p_kv_spare[10]} ]
set_property src_info {type:XDC file:3 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K20  [get_ports  {p_kv_spare[11]} ]
set_property src_info {type:XDC file:3 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L21  [get_ports  {p_kv_spare[12]} ]
set_property src_info {type:XDC file:3 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  R3   [get_ports  {n_ff1_recv[0]} ]
set_property src_info {type:XDC file:3 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P1   [get_ports  {n_ff1_recv[1]} ]
set_property src_info {type:XDC file:3 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N3   [get_ports  {n_ff1_recv[2]} ]
set_property src_info {type:XDC file:3 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M1   [get_ports  {n_ff1_recv[3]} ]
set_property src_info {type:XDC file:3 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L3   [get_ports  {n_ff1_recv[4]} ]
set_property src_info {type:XDC file:3 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K1   [get_ports  {n_ff1_recv[5]} ]
set_property src_info {type:XDC file:3 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J3   [get_ports  {n_ff1_recv[6]} ]
set_property src_info {type:XDC file:3 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H1   [get_ports  {n_ff1_recv[7]} ]
set_property src_info {type:XDC file:3 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G3   [get_ports  {n_ff1_recv[8]} ]
set_property src_info {type:XDC file:3 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F1   [get_ports  {n_ff1_recv[9]} ]
set_property src_info {type:XDC file:3 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  E3   [get_ports  {n_ff1_recv[10]} ]
set_property src_info {type:XDC file:3 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  D1   [get_ports  {n_ff1_recv[11]} ]
set_property src_info {type:XDC file:3 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  R4   [get_ports  {p_ff1_recv[0]} ]
set_property src_info {type:XDC file:3 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P2   [get_ports  {p_ff1_recv[1]} ]
set_property src_info {type:XDC file:3 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N4   [get_ports  {p_ff1_recv[2]} ]
set_property src_info {type:XDC file:3 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M2   [get_ports  {p_ff1_recv[3]} ]
set_property src_info {type:XDC file:3 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L4   [get_ports  {p_ff1_recv[4]} ]
set_property src_info {type:XDC file:3 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K2   [get_ports  {p_ff1_recv[5]} ]
set_property src_info {type:XDC file:3 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J4   [get_ports  {p_ff1_recv[6]} ]
set_property src_info {type:XDC file:3 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H2   [get_ports  {p_ff1_recv[7]} ]
set_property src_info {type:XDC file:3 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G4   [get_ports  {p_ff1_recv[8]} ]
set_property src_info {type:XDC file:3 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F2   [get_ports  {p_ff1_recv[9]} ]
set_property src_info {type:XDC file:3 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  E4   [get_ports  {p_ff1_recv[10]} ]
set_property src_info {type:XDC file:3 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  D2   [get_ports  {p_ff1_recv[11]} ]
set_property src_info {type:XDC file:3 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  R7   [get_ports  {n_ff1_xmit[0]} ]
set_property src_info {type:XDC file:3 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P5   [get_ports  {n_ff1_xmit[1]} ]
set_property src_info {type:XDC file:3 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N7   [get_ports  {n_ff1_xmit[2]} ]
set_property src_info {type:XDC file:3 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M5   [get_ports  {n_ff1_xmit[3]} ]
set_property src_info {type:XDC file:3 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L7   [get_ports  {n_ff1_xmit[4]} ]
set_property src_info {type:XDC file:3 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K5   [get_ports  {n_ff1_xmit[5]} ]
set_property src_info {type:XDC file:3 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J7   [get_ports  {n_ff1_xmit[6]} ]
set_property src_info {type:XDC file:3 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H5   [get_ports  {n_ff1_xmit[7]} ]
set_property src_info {type:XDC file:3 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H9   [get_ports  {n_ff1_xmit[8]} ]
set_property src_info {type:XDC file:3 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G7   [get_ports  {n_ff1_xmit[9]} ]
set_property src_info {type:XDC file:3 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F5   [get_ports  {n_ff1_xmit[10]} ]
set_property src_info {type:XDC file:3 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F9   [get_ports  {n_ff1_xmit[11]} ]
set_property src_info {type:XDC file:3 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  R8   [get_ports  {p_ff1_xmit[0]} ]
set_property src_info {type:XDC file:3 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P6   [get_ports  {p_ff1_xmit[1]} ]
set_property src_info {type:XDC file:3 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N8   [get_ports  {p_ff1_xmit[2]} ]
set_property src_info {type:XDC file:3 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M6   [get_ports  {p_ff1_xmit[3]} ]
set_property src_info {type:XDC file:3 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L8   [get_ports  {p_ff1_xmit[4]} ]
set_property src_info {type:XDC file:3 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K6   [get_ports  {p_ff1_xmit[5]} ]
set_property src_info {type:XDC file:3 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J8   [get_ports  {p_ff1_xmit[6]} ]
set_property src_info {type:XDC file:3 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H6   [get_ports  {p_ff1_xmit[7]} ]
set_property src_info {type:XDC file:3 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H10  [get_ports  {p_ff1_xmit[8]} ]
set_property src_info {type:XDC file:3 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G8   [get_ports  {p_ff1_xmit[9]} ]
set_property src_info {type:XDC file:3 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F6   [get_ports  {p_ff1_xmit[10]} ]
set_property src_info {type:XDC file:3 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F10  [get_ports  {p_ff1_xmit[11]} ]
set_property src_info {type:XDC file:3 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AG3  [get_ports  {n_ff2_recv[0]} ]
set_property src_info {type:XDC file:3 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF1  [get_ports  {n_ff2_recv[1]} ]
set_property src_info {type:XDC file:3 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AE3  [get_ports  {n_ff2_recv[2]} ]
set_property src_info {type:XDC file:3 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AD1  [get_ports  {n_ff2_recv[3]} ]
set_property src_info {type:XDC file:3 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AC3  [get_ports  {n_ff2_recv[4]} ]
set_property src_info {type:XDC file:3 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AB1  [get_ports  {n_ff2_recv[5]} ]
set_property src_info {type:XDC file:3 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AA3  [get_ports  {n_ff2_recv[6]} ]
set_property src_info {type:XDC file:3 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y1   [get_ports  {n_ff2_recv[7]} ]
set_property src_info {type:XDC file:3 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W3   [get_ports  {n_ff2_recv[8]} ]
set_property src_info {type:XDC file:3 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V1   [get_ports  {n_ff2_recv[9]} ]
set_property src_info {type:XDC file:3 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U3   [get_ports  {n_ff2_recv[10]} ]
set_property src_info {type:XDC file:3 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  T1   [get_ports  {n_ff2_recv[11]} ]
set_property src_info {type:XDC file:3 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AG4  [get_ports  {p_ff2_recv[0]} ]
set_property src_info {type:XDC file:3 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF2  [get_ports  {p_ff2_recv[1]} ]
set_property src_info {type:XDC file:3 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AE4  [get_ports  {p_ff2_recv[2]} ]
set_property src_info {type:XDC file:3 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AD2  [get_ports  {p_ff2_recv[3]} ]
set_property src_info {type:XDC file:3 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AC4  [get_ports  {p_ff2_recv[4]} ]
set_property src_info {type:XDC file:3 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AB2  [get_ports  {p_ff2_recv[5]} ]
set_property src_info {type:XDC file:3 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AA4  [get_ports  {p_ff2_recv[6]} ]
set_property src_info {type:XDC file:3 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y2   [get_ports  {p_ff2_recv[7]} ]
set_property src_info {type:XDC file:3 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W4   [get_ports  {p_ff2_recv[8]} ]
set_property src_info {type:XDC file:3 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V2   [get_ports  {p_ff2_recv[9]} ]
set_property src_info {type:XDC file:3 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U4   [get_ports  {p_ff2_recv[10]} ]
set_property src_info {type:XDC file:3 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  T2   [get_ports  {p_ff2_recv[11]} ]
set_property src_info {type:XDC file:3 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AG7  [get_ports  {n_ff2_xmit[0]} ]
set_property src_info {type:XDC file:3 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF5  [get_ports  {n_ff2_xmit[1]} ]
set_property src_info {type:XDC file:3 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AE7  [get_ports  {n_ff2_xmit[2]} ]
set_property src_info {type:XDC file:3 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AD5  [get_ports  {n_ff2_xmit[3]} ]
set_property src_info {type:XDC file:3 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AC7  [get_ports  {n_ff2_xmit[4]} ]
set_property src_info {type:XDC file:3 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AB5  [get_ports  {n_ff2_xmit[5]} ]
set_property src_info {type:XDC file:3 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AA7  [get_ports  {n_ff2_xmit[6]} ]
set_property src_info {type:XDC file:3 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y5   [get_ports  {n_ff2_xmit[7]} ]
set_property src_info {type:XDC file:3 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W7   [get_ports  {n_ff2_xmit[8]} ]
set_property src_info {type:XDC file:3 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V5   [get_ports  {n_ff2_xmit[9]} ]
set_property src_info {type:XDC file:3 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U7   [get_ports  {n_ff2_xmit[10]} ]
set_property src_info {type:XDC file:3 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  T5   [get_ports  {n_ff2_xmit[11]} ]
set_property src_info {type:XDC file:3 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AG8  [get_ports  {p_ff2_xmit[0]} ]
set_property src_info {type:XDC file:3 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF6  [get_ports  {p_ff2_xmit[1]} ]
set_property src_info {type:XDC file:3 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AE8  [get_ports  {p_ff2_xmit[2]} ]
set_property src_info {type:XDC file:3 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AD6  [get_ports  {p_ff2_xmit[3]} ]
set_property src_info {type:XDC file:3 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AC8  [get_ports  {p_ff2_xmit[4]} ]
set_property src_info {type:XDC file:3 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AB6  [get_ports  {p_ff2_xmit[5]} ]
set_property src_info {type:XDC file:3 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AA8  [get_ports  {p_ff2_xmit[6]} ]
set_property src_info {type:XDC file:3 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  Y6   [get_ports  {p_ff2_xmit[7]} ]
set_property src_info {type:XDC file:3 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W8   [get_ports  {p_ff2_xmit[8]} ]
set_property src_info {type:XDC file:3 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V6   [get_ports  {p_ff2_xmit[9]} ]
set_property src_info {type:XDC file:3 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U8   [get_ports  {p_ff2_xmit[10]} ]
set_property src_info {type:XDC file:3 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  T6   [get_ports  {p_ff2_xmit[11]} ]
set_property src_info {type:XDC file:3 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AW3  [get_ports  {n_ff3_recv[0]} ]
set_property src_info {type:XDC file:3 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AV1  [get_ports  {n_ff3_recv[1]} ]
set_property src_info {type:XDC file:3 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AU3  [get_ports  {n_ff3_recv[2]} ]
set_property src_info {type:XDC file:3 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AT1  [get_ports  {n_ff3_recv[3]} ]
set_property src_info {type:XDC file:3 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AR3  [get_ports  {n_ff3_recv[4]} ]
set_property src_info {type:XDC file:3 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AP1  [get_ports  {n_ff3_recv[5]} ]
set_property src_info {type:XDC file:3 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AN3  [get_ports  {n_ff3_recv[6]} ]
set_property src_info {type:XDC file:3 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AM1  [get_ports  {n_ff3_recv[7]} ]
set_property src_info {type:XDC file:3 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AL3  [get_ports  {n_ff3_recv[8]} ]
set_property src_info {type:XDC file:3 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AK1  [get_ports  {n_ff3_recv[9]} ]
set_property src_info {type:XDC file:3 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AJ3  [get_ports  {n_ff3_recv[10]} ]
set_property src_info {type:XDC file:3 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AH1  [get_ports  {n_ff3_recv[11]} ]
set_property src_info {type:XDC file:3 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AW4  [get_ports  {p_ff3_recv[0]} ]
set_property src_info {type:XDC file:3 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AV2  [get_ports  {p_ff3_recv[1]} ]
set_property src_info {type:XDC file:3 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AU4  [get_ports  {p_ff3_recv[2]} ]
set_property src_info {type:XDC file:3 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AT2  [get_ports  {p_ff3_recv[3]} ]
set_property src_info {type:XDC file:3 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AR4  [get_ports  {p_ff3_recv[4]} ]
set_property src_info {type:XDC file:3 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AP2  [get_ports  {p_ff3_recv[5]} ]
set_property src_info {type:XDC file:3 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AN4  [get_ports  {p_ff3_recv[6]} ]
set_property src_info {type:XDC file:3 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AM2  [get_ports  {p_ff3_recv[7]} ]
set_property src_info {type:XDC file:3 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AL4  [get_ports  {p_ff3_recv[8]} ]
set_property src_info {type:XDC file:3 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AK2  [get_ports  {p_ff3_recv[9]} ]
set_property src_info {type:XDC file:3 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AJ4  [get_ports  {p_ff3_recv[10]} ]
set_property src_info {type:XDC file:3 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AH2  [get_ports  {p_ff3_recv[11]} ]
set_property src_info {type:XDC file:3 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AT9  [get_ports  {n_ff3_xmit[0]} ]
set_property src_info {type:XDC file:3 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AT5  [get_ports  {n_ff3_xmit[1]} ]
set_property src_info {type:XDC file:3 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AR7  [get_ports  {n_ff3_xmit[2]} ]
set_property src_info {type:XDC file:3 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AP9  [get_ports  {n_ff3_xmit[3]} ]
set_property src_info {type:XDC file:3 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AP5  [get_ports  {n_ff3_xmit[4]} ]
set_property src_info {type:XDC file:3 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AN7  [get_ports  {n_ff3_xmit[5]} ]
set_property src_info {type:XDC file:3 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AM9  [get_ports  {n_ff3_xmit[6]} ]
set_property src_info {type:XDC file:3 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AM5  [get_ports  {n_ff3_xmit[7]} ]
set_property src_info {type:XDC file:3 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AL7  [get_ports  {n_ff3_xmit[8]} ]
set_property src_info {type:XDC file:3 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AK5  [get_ports  {n_ff3_xmit[9]} ]
set_property src_info {type:XDC file:3 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AJ7  [get_ports  {n_ff3_xmit[10]} ]
set_property src_info {type:XDC file:3 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AH5  [get_ports  {n_ff3_xmit[11]} ]
set_property src_info {type:XDC file:3 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AT10 [get_ports  {p_ff3_xmit[0]} ]
set_property src_info {type:XDC file:3 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AT6  [get_ports  {p_ff3_xmit[1]} ]
set_property src_info {type:XDC file:3 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AR8  [get_ports  {p_ff3_xmit[2]} ]
set_property src_info {type:XDC file:3 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AP10 [get_ports  {p_ff3_xmit[3]} ]
set_property src_info {type:XDC file:3 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AP6  [get_ports  {p_ff3_xmit[4]} ]
set_property src_info {type:XDC file:3 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AN8  [get_ports  {p_ff3_xmit[5]} ]
set_property src_info {type:XDC file:3 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AM10 [get_ports  {p_ff3_xmit[6]} ]
set_property src_info {type:XDC file:3 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AM6  [get_ports  {p_ff3_xmit[7]} ]
set_property src_info {type:XDC file:3 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AL8  [get_ports  {p_ff3_xmit[8]} ]
set_property src_info {type:XDC file:3 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AK6  [get_ports  {p_ff3_xmit[9]} ]
set_property src_info {type:XDC file:3 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AJ8  [get_ports  {p_ff3_xmit[10]} ]
set_property src_info {type:XDC file:3 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AH6  [get_ports  {p_ff3_xmit[11]} ]
set_property src_info {type:XDC file:3 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H42  [get_ports  {n_ff4_recv[0]} ]
set_property src_info {type:XDC file:3 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G40  [get_ports  {n_ff4_recv[1]} ]
set_property src_info {type:XDC file:3 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F42  [get_ports  {n_ff4_recv[2]} ]
set_property src_info {type:XDC file:3 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  E40  [get_ports  {n_ff4_recv[3]} ]
set_property src_info {type:XDC file:3 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  H41  [get_ports  {p_ff4_recv[0]} ]
set_property src_info {type:XDC file:3 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  G39  [get_ports  {p_ff4_recv[1]} ]
set_property src_info {type:XDC file:3 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  F41  [get_ports  {p_ff4_recv[2]} ]
set_property src_info {type:XDC file:3 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  E39  [get_ports  {p_ff4_recv[3]} ]
set_property src_info {type:XDC file:3 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P37  [get_ports  {n_ff4_xmit[0]} ]
set_property src_info {type:XDC file:3 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N35  [get_ports  {n_ff4_xmit[1]} ]
set_property src_info {type:XDC file:3 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M37  [get_ports  {n_ff4_xmit[2]} ]
set_property src_info {type:XDC file:3 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L35  [get_ports  {n_ff4_xmit[3]} ]
set_property src_info {type:XDC file:3 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P36  [get_ports  {p_ff4_xmit[0]} ]
set_property src_info {type:XDC file:3 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N34  [get_ports  {p_ff4_xmit[1]} ]
set_property src_info {type:XDC file:3 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M36  [get_ports  {p_ff4_xmit[2]} ]
set_property src_info {type:XDC file:3 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L34  [get_ports  {p_ff4_xmit[3]} ]
set_property src_info {type:XDC file:3 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M42  [get_ports  {n_ff5_recv[0]} ]
set_property src_info {type:XDC file:3 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L40  [get_ports  {n_ff5_recv[1]} ]
set_property src_info {type:XDC file:3 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K42  [get_ports  {n_ff5_recv[2]} ]
set_property src_info {type:XDC file:3 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J40  [get_ports  {n_ff5_recv[3]} ]
set_property src_info {type:XDC file:3 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  M41  [get_ports  {p_ff5_recv[0]} ]
set_property src_info {type:XDC file:3 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  L39  [get_ports  {p_ff5_recv[1]} ]
set_property src_info {type:XDC file:3 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  K41  [get_ports  {p_ff5_recv[2]} ]
set_property src_info {type:XDC file:3 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J39  [get_ports  {p_ff5_recv[3]} ]
set_property src_info {type:XDC file:3 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U35  [get_ports  nk_ff5_xmit0 ]
set_property src_info {type:XDC file:3 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  T37  [get_ports  {n_ff5_xmit[1]} ]
set_property src_info {type:XDC file:3 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  R39  [get_ports  {n_ff5_xmit[2]} ]
set_property src_info {type:XDC file:3 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  R35  [get_ports  {n_ff5_xmit[3]} ]
set_property src_info {type:XDC file:3 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U34  [get_ports  {p_ff5_xmit[0]} ]
set_property src_info {type:XDC file:3 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  T36  [get_ports  {p_ff5_xmit[1]} ]
set_property src_info {type:XDC file:3 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  R38  [get_ports  {p_ff5_xmit[2]} ]
set_property src_info {type:XDC file:3 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  R34  [get_ports  {p_ff5_xmit[3]} ]
set_property src_info {type:XDC file:3 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V42  [get_ports  {n_ff6_recv[0]} ]
set_property src_info {type:XDC file:3 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  T42  [get_ports  {n_ff6_recv[1]} ]
set_property src_info {type:XDC file:3 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P42  [get_ports  {n_ff6_recv[2]} ]
set_property src_info {type:XDC file:3 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N40  [get_ports  {n_ff6_recv[3]} ]
set_property src_info {type:XDC file:3 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V41  [get_ports  {p_ff6_recv[0]} ]
set_property src_info {type:XDC file:3 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  T41  [get_ports  {p_ff6_recv[1]} ]
set_property src_info {type:XDC file:3 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  P41  [get_ports  {p_ff6_recv[2]} ]
set_property src_info {type:XDC file:3 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  N39  [get_ports  {p_ff6_recv[3]} ]
set_property src_info {type:XDC file:3 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W39  [get_ports  {n_ff6_xmit[0]} ]
set_property src_info {type:XDC file:3 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W35  [get_ports  {n_ff6_xmit[1]} ]
set_property src_info {type:XDC file:3 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V37  [get_ports  {n_ff6_xmit[2]} ]
set_property src_info {type:XDC file:3 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U39  [get_ports  {n_ff6_xmit[3]} ]
set_property src_info {type:XDC file:3 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W38  [get_ports  {p_ff6_xmit[0]} ]
set_property src_info {type:XDC file:3 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  W34  [get_ports  {p_ff6_xmit[1]} ]
set_property src_info {type:XDC file:3 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  V36  [get_ports  {p_ff6_xmit[2]} ]
set_property src_info {type:XDC file:3 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  U38  [get_ports  {p_ff6_xmit[3]} ]
set_property src_info {type:XDC file:3 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AE40 [get_ports  {n_ff7_recv[0]} ]
set_property src_info {type:XDC file:3 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF42 [get_ports  {n_ff7_recv[1]} ]
set_property src_info {type:XDC file:3 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AG40 [get_ports  {n_ff7_recv[2]} ]
set_property src_info {type:XDC file:3 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AH42 [get_ports  {n_ff7_recv[3]} ]
set_property src_info {type:XDC file:3 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AJ40 [get_ports  {n_ff7_recv[4]} ]
set_property src_info {type:XDC file:3 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AK42 [get_ports  {n_ff7_recv[5]} ]
set_property src_info {type:XDC file:3 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AL40 [get_ports  {n_ff7_recv[6]} ]
set_property src_info {type:XDC file:3 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AM42 [get_ports  {n_ff7_recv[7]} ]
set_property src_info {type:XDC file:3 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AN40 [get_ports  {n_ff7_recv[8]} ]
set_property src_info {type:XDC file:3 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AP42 [get_ports  {n_ff7_recv[9]} ]
set_property src_info {type:XDC file:3 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AR40 [get_ports  {n_ff7_recv[10]} ]
set_property src_info {type:XDC file:3 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AT42 [get_ports  {n_ff7_recv[11]} ]
set_property src_info {type:XDC file:3 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AE39 [get_ports  {p_ff7_recv[0]} ]
set_property src_info {type:XDC file:3 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF41 [get_ports  {p_ff7_recv[1]} ]
set_property src_info {type:XDC file:3 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AG39 [get_ports  {p_ff7_recv[2]} ]
set_property src_info {type:XDC file:3 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AH41 [get_ports  {p_ff7_recv[3]} ]
set_property src_info {type:XDC file:3 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AJ39 [get_ports  {p_ff7_recv[4]} ]
set_property src_info {type:XDC file:3 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AK41 [get_ports  {p_ff7_recv[5]} ]
set_property src_info {type:XDC file:3 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AL39 [get_ports  {p_ff7_recv[6]} ]
set_property src_info {type:XDC file:3 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AM41 [get_ports  {p_ff7_recv[7]} ]
set_property src_info {type:XDC file:3 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AN39 [get_ports  {p_ff7_recv[8]} ]
set_property src_info {type:XDC file:3 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AP41 [get_ports  {p_ff7_recv[9]} ]
set_property src_info {type:XDC file:3 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AR39 [get_ports  {p_ff7_recv[10]} ]
set_property src_info {type:XDC file:3 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AT41 [get_ports  {p_ff7_recv[11]} ]
set_property src_info {type:XDC file:3 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AC35 [get_ports  {n_ff7_xmit[0]} ]
set_property src_info {type:XDC file:3 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AD37 [get_ports  {n_ff7_xmit[1]} ]
set_property src_info {type:XDC file:3 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AE35 [get_ports  {n_ff7_xmit[2]} ]
set_property src_info {type:XDC file:3 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF37 [get_ports  {n_ff7_xmit[3]} ]
set_property src_info {type:XDC file:3 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF33 [get_ports  {n_ff7_xmit[4]} ]
set_property src_info {type:XDC file:3 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AG35 [get_ports  {n_ff7_xmit[5]} ]
set_property src_info {type:XDC file:3 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AH37 [get_ports  {n_ff7_xmit[6]} ]
set_property src_info {type:XDC file:3 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AH33 [get_ports  {n_ff7_xmit[7]} ]
set_property src_info {type:XDC file:3 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AJ35 [get_ports  {n_ff7_xmit[8]} ]
set_property src_info {type:XDC file:3 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AK37 [get_ports  {n_ff7_xmit[9]} ]
set_property src_info {type:XDC file:3 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AL35 [get_ports  {n_ff7_xmit[10]} ]
set_property src_info {type:XDC file:3 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AM37 [get_ports  {n_ff7_xmit[11]} ]
set_property src_info {type:XDC file:3 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AC34 [get_ports  {p_ff7_xmit[0]} ]
set_property src_info {type:XDC file:3 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AD36 [get_ports  {p_ff7_xmit[1]} ]
set_property src_info {type:XDC file:3 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AE34 [get_ports  {p_ff7_xmit[2]} ]
set_property src_info {type:XDC file:3 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF36 [get_ports  {p_ff7_xmit[3]} ]
set_property src_info {type:XDC file:3 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AF32 [get_ports  {p_ff7_xmit[4]} ]
set_property src_info {type:XDC file:3 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AG34 [get_ports  {p_ff7_xmit[5]} ]
set_property src_info {type:XDC file:3 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AH36 [get_ports  {p_ff7_xmit[6]} ]
set_property src_info {type:XDC file:3 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AH32 [get_ports  {p_ff7_xmit[7]} ]
set_property src_info {type:XDC file:3 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AJ34 [get_ports  {p_ff7_xmit[8]} ]
set_property src_info {type:XDC file:3 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AK36 [get_ports  {p_ff7_xmit[9]} ]
set_property src_info {type:XDC file:3 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AL34 [get_ports  {p_ff7_xmit[10]} ]
set_property src_info {type:XDC file:3 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AM36 [get_ports  {p_ff7_xmit[11]} ]
set_property src_info {type:XDC file:3 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVDS [get_ports *_test_conn*]
set_property src_info {type:XDC file:3 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  BB16 [get_ports  {n_test_conn[0]} ]
set_property src_info {type:XDC file:3 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  BB14 [get_ports  {n_test_conn[1]} ]
set_property src_info {type:XDC file:3 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AY15 [get_ports  {n_test_conn[2]} ]
set_property src_info {type:XDC file:3 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AV14 [get_ports  {n_test_conn[3]} ]
set_property src_info {type:XDC file:3 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AR12 [get_ports  {n_test_conn[4]} ]
set_property src_info {type:XDC file:3 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AP12 [get_ports  {n_test_conn[5]} ]
set_property src_info {type:XDC file:3 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  BB17 [get_ports  {p_test_conn[0]} ]
set_property src_info {type:XDC file:3 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  BA14 [get_ports  {p_test_conn[1]} ]
set_property src_info {type:XDC file:3 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AY16 [get_ports  {p_test_conn[2]} ]
set_property src_info {type:XDC file:3 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AU14 [get_ports  {p_test_conn[3]} ]
set_property src_info {type:XDC file:3 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AR13 [get_ports  {p_test_conn[4]} ]
set_property src_info {type:XDC file:3 line:552 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AP13 [get_ports  {p_test_conn[5]} ]
set_property src_info {type:XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 25.000 -waveform {0.000 12.5000} [get_nets amc13_clk_40]
set_property src_info {type:SCOPED_XDC file:5 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports m_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:5 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports axi_c2c_phy_clk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:5 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_disable_timing -from CLK -to O [filter [all_fanout -from [get_ports m_axi_lite_aclk] -flat -endpoints_only -only_cells] {PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==LUTRAM}]
set_property src_info {type:SCOPED_XDC file:5 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_pins -hierarchical -filter {NAME =~*axi_lite_slave_gen.reset_sync_lite_slv/sync_reset_out_reg/C}] -to [get_pins -hierarchical -filter {NAME =~*axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/fifo_reset_reg/PRE}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/m_axi_lite_aclk]]]
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:6 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:7 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:8 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:9 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:10 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:11 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:12 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:13 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:14 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_ar_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:15 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_aw_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:16 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_b_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:17 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:18 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:19 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:20 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:21 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:22 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:23 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_r_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:24 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/slave_fpga_gen.axi_chip2chip_slave_inst/axi_chip2chip_w_fifo_inst/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:25 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:26 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:27 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:28 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:29 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:30 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:31 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_rx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:32 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
current_instance
current_instance c2csslave_wrapper_1/c2cSlave_i/C2CLink/inst/axi_lite_slave_gen.axi_chip2chip_lite_slave_inst/axi_chip2chip_lite_slave_tx_fifo/axi_chip2chip_async_fifo_inst/xpm_fifo_async_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:33 line:16 export:INPUT save:NONE read:READ} [current_design]
set_bus_skew -from [get_cells src_gray_ff_reg*] -to [get_cells {dest_graysync_ff_reg[0]*}] 20.000
