AXI_CONTROL_SETS:
  AXI_MASTER_CTRL:
      axi_interconnect: "${::AXI_INTERCONNECT_NAME}"
      axi_clk: "${::AXI_MASTER_CLK}"
      axi_rstn: "${::AXI_MASTER_RSTN}"
      axi_freq: "${::AXI_MASTER_CLK_FREQ}"

AXI_SLAVES:
  V_C2C_PHY:
    TCL_CALL: 
      command: AXI_DEV_CONNECT
      axi_control: 
        axi_interconnect: "${::AXI_INTERCONNECT_NAME}"
        axi_clk: "${::EXT_CLK}"
        axi_rstn: "${::EXT_RESET}"
        axi_freq: "${::EXT_CLK_FREQ}"

      addr:
        offset: "0x83D44000"
        range:  "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/DRP_USP_GTY.xml"
    UHAL_BASE: 0xC6000000
  VIRTEX_SYS_MGMT:
    TCL_CALL:
      command: AXI_IP_SYS_MGMT
      enable_i2c_pins: 1
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x83D42000"
        range: "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/VIRTEX_SYS_MGMT.xml"
    UHAL_BASE: 0xC0000000
  K_IO:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x83d40000"
        range:  "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/V_IO.xml"
    UHAL_BASE: 0xC1000000
    HDL: "src/CM_IO"    
  CM_V_INFO:
    TCL_CALL:
      command: AXI_PL_DEV_CONNECT 
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0x83d43000"
        range:  "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/FW_INFO.xml"
    UHAL_BASE: 0xC2000000
    HDL: "src/CM_FW_info"
  VIRTEX_IPBUS:
    TCL_CALL:
      command: AXI_PL_DEV_CONNECT 
      axi_control: "${::AXI_MASTER_CTRL}"
      type: "AXI4"
      addr:
        offset: "0x8C000000"
        range:  "32M"
      remote_slave: "1"
      data_width: "64"
    XML:
      - "address_table/modules/IPBUS.xml"
    UHAL_BASE: 0xC5000000    





