AXI_SLAVES:
  VIRTEX_SYS_MGMT:
    TCL_CALL: "[AXI_IP_SYS_MGMT 1 VIRTEX_SYS_MGMT         ${AXI_INTERCONNECT_NAME} ${AXI_MASTER_CLK} ${AXI_MASTER_RSTN} 50000000 0x83D42000 4K 0]"
    XML:
      - "address_table/modules/VIRTEX_SYS_MGMT.xml"
    UHAL_BASE: 0xC0000000
  
  V_IO:
    TCL_CALL: "[AXI_PL_DEV_CONNECT V_IO                 ${AXI_INTERCONNECT_NAME} ${AXI_MASTER_CLK} ${AXI_MASTER_RSTN} 50000000 0x83D40000 4K]"
    XML:
      - "address_table/modules/V_IO.xml"
    UHAL_BASE: 0xC1000000
    HDL: "src/V_IO"    
  
  CM_V_INFO:
    TCL_CALL: "[AXI_PL_DEV_CONNECT CM_V_INFO            ${AXI_INTERCONNECT_NAME} ${AXI_MASTER_CLK} ${AXI_MASTER_RSTN} 50000000 0x83D43000 4K]"
    XML:
      - "address_table/modules/FW_INFO.xml"
    UHAL_BASE: 0xC2000000
    HDL: "src/CM_V_info"
                  
  VIRTEX_IPBUS:
    TCL_CALL: "[AXI_PL_DEV_CONNECT VIRTEX_IPBUS         ${AXI_INTERCONNECT_NAME} ${AXI_MASTER_CLK} ${AXI_MASTER_RSTN} 50000000 0x8C000000 32M AXI4]"
    XML:
      - "address_table/modules/IPBUS.xml"
    UHAL_BASE: 0xC5000000    
  
  V_C2C_PHY:
    TCL_CALL: "[AXI_DEV_CONNECT V_C2C_PHY               ${AXI_INTERCONNECT_NAME} ${EXT_CLK} ${EXT_RESET} 50000000 0x83D44000 4K 0]"
    XML:
      - "address_table/modules/DRP_USP_GTY.xml"
    UHAL_BASE: 0xC6000000
