
# file: ibert_ultrascale_gty_0.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_ultrascale_gty_0.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##

set_property C_CLK_INPUT_FREQ_HZ 312500000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
##
##gtrefclk lock constraints
##
set_property PACKAGE_PIN AT39 [get_ports gty_refclk0p_i[0]]
set_property PACKAGE_PIN AT40 [get_ports gty_refclk0n_i[0]]
set_property PACKAGE_PIN AR41 [get_ports gty_refclk1p_i[0]]
set_property PACKAGE_PIN AR42 [get_ports gty_refclk1n_i[0]]
set_property PACKAGE_PIN AA41 [get_ports gty_refclk0p_i[1]]
set_property PACKAGE_PIN AA42 [get_ports gty_refclk0n_i[1]]
set_property PACKAGE_PIN Y39 [get_ports gty_refclk1p_i[1]]
set_property PACKAGE_PIN Y40 [get_ports gty_refclk1n_i[1]]
set_property PACKAGE_PIN W41 [get_ports gty_refclk0p_i[2]]
set_property PACKAGE_PIN W42 [get_ports gty_refclk0n_i[2]]
set_property PACKAGE_PIN V39 [get_ports gty_refclk1p_i[2]]
set_property PACKAGE_PIN V40 [get_ports gty_refclk1n_i[2]]
##
## Refclk constraints
##
create_clock -name gtrefclk0_4 -period 3.2 [get_ports gty_refclk0p_i[0]]
create_clock -name gtrefclk1_4 -period 3.2 [get_ports gty_refclk1p_i[0]]
set_clock_groups -group [get_clocks gtrefclk0_4 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_4 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_9 -period 3.2 [get_ports gty_refclk0p_i[1]]
create_clock -name gtrefclk1_9 -period 3.2 [get_ports gty_refclk1p_i[1]]
set_clock_groups -group [get_clocks gtrefclk0_9 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_9 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_10 -period 3.2 [get_ports gty_refclk0p_i[2]]
create_clock -name gtrefclk1_10 -period 3.2 [get_ports gty_refclk1p_i[2]]
set_clock_groups -group [get_clocks gtrefclk0_10 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_10 -include_generated_clocks] -asynchronous
