AXI_CONTROL_SETS:
  AXI_MASTER_CTRL:
      axi_interconnect: "${::AXI_INTERCONNECT_NAME}"
      axi_clk: "${::AXI_MASTER_CLK}"
      axi_rstn: "${::AXI_MASTER_RSTN}"
      axi_freq: "${::AXI_MASTER_CLK_FREQ}"

AXI_SLAVES:
  KINTEX_SYS_MGMT:
    TCL_CALL:
      command: AXI_IP_SYS_MGMT
      enable_i2c_pins: 1
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xB1001000"
        range: "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/KINTEX_SYS_MGMT.xml"
    UHAL_BASE: 0x80000000
  
  K_IO:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xB1002000"
        range:  "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/CM_IO.xml"
      - "address_table/modules/CM_C2C_DEBUG_USP.xml"
      - "address_table/modules/CM_C2C_Status.xml"
    UHAL_BASE: 0x81000000
    HDL: 
      out_dir: "configs/Cornell_rev1_p1_KU15p-2-SM_USP/autogen/CM_IO"    
      map_template: "axi_generic/template_map.vhd"
  
  CM_K_INFO:
    TCL_CALL:
      command: AXI_PL_DEV_CONNECT 
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xB1003000"
        range:  "4K"
      remote_slave: "1"
    XML:
      - "address_table/modules/FW_INFO.xml"
    UHAL_BASE: 0x82000000
    HDL: 
      out_dir: "configs/Cornell_rev1_p1_KU15p-2-SM_USP/autogen/CM_FW_info"
      map_template: "axi_generic/template_map.vhd"

  K_C2C_INTF:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xB1004000"
        range:  "8K"
      remote_slave: "1"
    XML:
      - "address_table/modules/C2C_INTFS.xml"
      - "address_table/modules/C2C_INTF.xml"
      - "address_table/modules/DRP_USP_GTH.xml"
      - "address_table/modules/CM_C2C_Status.xml"
      - "address_table/modules/CM_C2C_DEBUG_USP.xml"
      - "address_table/modules/CM_C2C_CNT.xml"
    UHAL_BASE: 0x86000000
    HDL: 
      out_dir: "configs/Cornell_rev1_p1_KU15p-2-SM_USP/autogen/C2C_INTF"    
      map_template: "axi_generic/template_map_withbram.vhd"
                
  KINTEX_IPBUS:
    TCL_CALL:
      command: AXI_PL_DEV_CONNECT 
      axi_control: "${::AXI_MASTER_CTRL}"
      type: "AXI4"
      addr:
        offset: "0xB0000000"
        range:  "16M"
      data_width: "64"
      remote_slave: "1"
    XML:
      - "address_table/modules/IPBUS.xml"
    UHAL_BASE: 0x85000000    
  QUAD_TEST:
    TCL_CALL:
      command: AXI_PL_DEV_CONNECT
      axi_control: "${::AXI_MASTER_CTRL}"
      addr:
        offset: "0xB1100000"
        range:  "1M"
      remote_slave: "1"
    XML: 
      - "address_table/modules/QuadTest.xml"
      - "address_table/modules/QuadTest_FF_4_GTY.xml"
      - "address_table/modules/USP_GTY_COMMON.xml"
      - "address_table/modules/USP_GTY_Channel.xml"
      - "address_table/modules/Channel_Status.xml"
      - "address_table/modules/Channel_DEBUG_USP.xml"
      - "address_table/modules/DRP_USP_GTY.xml"
    UHAL_BASE: 0x86000000
    HDL: 
      out_dir: "configs/Cornell_rev1_p1_KU15p-2-SM_USP/autogen/Quad_Test"
      map_template: "axi_generic/template_map_withbram.vhd"

CORES: 
  FF_K6:
    TCL_CALL:
      command: BuildMGTCores
      GT_TYPE: GTY
      freerun_frequency: 50
      clocking:
        TX:
          LINE_RATE: 25
          PLL_TYPE: QPLL0
          REFCLK_FREQUENCY: 312.5
          OUTCLK_SOURCE: TXOUTCLKPCS
        RX:
          LINE_RATE: 25
          PLL_TYPE: QPLL0
          REFCLK_FREQUENCY: 312.5    
          OUTCLK_SOURCE: RXOUTCLKPCS 
      protocol:
        TX:
          DATA_ENCODING: 64B66B
          USER_DATA_WIDTH: 64
        RX:
          DATA_DECODING: 64B66B
          USER_DATA_WIDTH: 64
      core:
        LOCATE_TX_USER_CLOCKING: CORE
        LOCATE_RX_USER_CLOCKING: CORE
        LOCATE_RESET_CONTROLLER: EXAMPLE_DESIGN
      links:
        X0Y16:
          RX: clk0
          TX: clk0
        X0Y17:
          RX: clk0
          TX: clk0
        X0Y18:
          RX: clk0
          TX: clk0
        X0Y19:
          RX: clk0
          TX: clk0
  FF_K5:
    TCL_CALL:
      command: BuildMGTCores
      GT_TYPE: GTY
      freerun_frequency: 50
      clocking:
        TX:
          LINE_RATE: 25
          PLL_TYPE: QPLL0
          REFCLK_FREQUENCY: 312.5
          OUTCLK_SOURCE: TXOUTCLKPMA 
        RX:
          LINE_RATE: 25
          PLL_TYPE: QPLL0
          REFCLK_FREQUENCY: 312.5    
          OUTCLK_SOURCE: RXOUTCLKPMA 
      protocol:
        TX:
          DATA_ENCODING: 64B66B
          USER_DATA_WIDTH: 64
        RX:
          DATA_DECODING: 64B66B
          USER_DATA_WIDTH: 64
      core:
        LOCATE_TX_USER_CLOCKING: CORE
        LOCATE_RX_USER_CLOCKING: CORE
        LOCATE_RESET_CONTROLLER: EXAMPLE_DESIGN
      links:
        X0Y20:
          RX: clk0-1
          TX: clk0-1
        X0Y21:
          RX: clk0-1
          TX: clk0-1
        X0Y22:
          RX: clk0-1
          TX: clk0-1
        X0Y23:
          RX: clk0-1
          TX: clk0-1
  FF_K4:
    TCL_CALL:
      command: BuildMGTCores
      GT_TYPE: GTY
      freerun_frequency: 50
      clocking:
        TX:
          LINE_RATE: 25
          PLL_TYPE: QPLL0
          REFCLK_FREQUENCY: 312.5
          OUTCLK_SOURCE: TXOUTCLKPMA
        RX:
          LINE_RATE: 25
          PLL_TYPE: QPLL0
          REFCLK_FREQUENCY: 312.5   
          OUTCLK_SOURCE: RXOUTCLKPMA 
      protocol:
        TX:
          DATA_ENCODING: 64B66B
          USER_DATA_WIDTH: 64
        RX:
          DATA_DECODING: 64B66B
          USER_DATA_WIDTH: 64
      core:
        LOCATE_TX_USER_CLOCKING: CORE
        LOCATE_RX_USER_CLOCKING: CORE
        LOCATE_RESET_CONTROLLER: EXAMPLE_DESIGN
      links:
        X0Y24:
          RX: clk0
          TX: clk0
        X0Y25:
          RX: clk0
          TX: clk0
        X0Y26:
          RX: clk0
          TX: clk0
        X0Y27:
          RX: clk0
          TX: clk0
