
# file: Cornell_rev1_p2_VU7p_ibert.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_Cornell_rev1_p2_VU7p_ibert.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##
create_clock -name D_CLK -period 5.0 [get_ports gty_sysclkp_i]
set_clock_groups -group [get_clocks D_CLK -include_generated_clocks] -asynchronous

set_property C_CLK_INPUT_FREQ_HZ 200000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
##
##gtrefclk lock constraints
##
set_property PACKAGE_PIN AT11 [get_ports gty_refclk0p_i[0]]
set_property PACKAGE_PIN AT10 [get_ports gty_refclk0n_i[0]]
set_property PACKAGE_PIN AP11 [get_ports gty_refclk1p_i[0]]
set_property PACKAGE_PIN AP10 [get_ports gty_refclk1n_i[0]]
##
## Refclk constraints
##
create_clock -name gtrefclk0_11 -period 3.119 [get_ports gty_refclk0p_i[0]]
create_clock -name gtrefclk1_11 -period 3.119 [get_ports gty_refclk1p_i[0]]
set_clock_groups -group [get_clocks gtrefclk0_11 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_11 -include_generated_clocks] -asynchronous
##
## System clock pin locs and timing constraints
##
set_property PACKAGE_PIN BA35 [get_ports gty_sysclkp_i]
set_property IOSTANDARD LVDS [get_ports gty_sysclkp_i]
