AXI_SLAVES:
  K_C2C_PHY:
    TCL_CALL: "[AXI_DEV_CONNECT K_C2C_PHY ${AXI_INTERCONNECT_NAME} ${EXT_CLK} ${EXT_RESET} 50000000 0xB3c44000 4K 0]"
    XML:
      - "address_table/modules/DRP_USP_GTY.xml"
    UHAL_BASE: 0x86000000

  KINTEX_SYS_MGMT:
    TCL_CALL: "[AXI_IP_SYS_MGMT KINTEX_SYS_MGMT         ${AXI_INTERCONNECT_NAME} ${AXI_MASTER_CLK} ${AXI_MASTER_RSTN} 50000000 0xB3c42000 4K 0]"
    XML:
      - "address_table/modules/KINTEX_SYS_MGMT.xml"
    UHAL_BASE: 0x80000000
  
  K_IO:
    TCL_CALL: "[AXI_PL_DEV_CONNECT K_IO                 ${AXI_INTERCONNECT_NAME} ${AXI_MASTER_CLK} ${AXI_MASTER_RSTN} 50000000 0xB3c40000 4K]"
    XML:
      - "address_table/modules/K_IO.xml"
    UHAL_BASE: 0x81000000
    HDL: "src/CM_IO"    
  
  CM_K_INFO:
    TCL_CALL: "[AXI_PL_DEV_CONNECT CM_K_INFO            ${AXI_INTERCONNECT_NAME} ${AXI_MASTER_CLK} ${AXI_MASTER_RSTN} 50000000 0xB3c43000 4K]"
    XML:
      - "address_table/modules/FW_INFO.xml"
    UHAL_BASE: 0x82000000
    HDL: "src/CM_FW_info"
                
  
  KINTEX_IPBUS:
    TCL_CALL: "[AXI_PL_DEV_CONNECT KINTEX_IPBUS         ${AXI_INTERCONNECT_NAME} ${AXI_MASTER_CLK} ${AXI_MASTER_RSTN} 50000000 0xBA000000 32M AXI4]"
    XML:
      - "address_table/modules/IPBUS.xml"
    UHAL_BASE: 0x85000000    
