#================================================================================
#  Configure and add AXI slaves
#  Auto-generated by 
#================================================================================
#KINTEX_SYS_MGMT
{'enable_i2c_pins': 1, 'axi_control': '${::AXI_MASTER_CTRL}', 'remote_slave': '1', 'command': 'AXI_IP_SYS_MGMT', 'addr': {'range': '4K', 'offset': '0xBE001000'}}

#KINTEX_IPBUS
{'axi_control': '${::AXI_MASTER_CTRL}', 'command': 'AXI_PL_DEV_CONNECT', 'addr': {'range': '32M', 'offset': '0xBA000000'}, 'remote_slave': '1', 'type': 'AXI4', 'data_width': '64'}

#CM_K_INFO
{'axi_control': '${::AXI_MASTER_CTRL}', 'remote_slave': '1', 'command': 'AXI_PL_DEV_CONNECT', 'addr': {'range': '4K', 'offset': '0xBE003000'}}

