AXI_CONTROL_SETS:
  AXI_MASTER_CTRL:
      axi_interconnect: "${::AXI_INTERCONNECT_NAME}"
      axi_clk: "${::AXI_MASTER_CLK}"
      axi_rstn: "${::AXI_MASTER_RSTN}"
      axi_freq: "${::AXI_MASTER_CLK_FREQ}"

AXI_SLAVES:
  K_C2C_PHY:
    TCL_CALL:
      command: AXI_DEV_CONNECT 
      axi_control:
        axi_interconnect: ${::AXI_INTERCONNECT_NAME} 
        axi_clk:          ${::EXT_CLK} 
        axi_rstn:         ${::EXT_RESET} 
        axi_freq:         ${::EXT_CLK_FREQ}
      addr:
        offset: "0xB3c44000"
        range: 4K
      remote_slave: 0
    XML:
      - "address_table/modules/DRP_USP_GTY.xml"
    UHAL_BASE: 0x86000000

  KINTEX_SYS_MGMT:
    TCL_CALL: 
      command: AXI_IP_SYS_MGMT
      enable_i2c_pins: 0  
      axi_control: ${::AXI_MASTER_CTRL}
      addr:
        offset: "0x83c42000"
        range: 4K
      remote_slave: 0
    XML:
      - "address_table/modules/KINTEX_SYS_MGMT.xml"
    UHAL_BASE: 0x80000000
  
  K_IO:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: ${::AXI_MASTER_CTRL}
      addr:
        offset: "0x83c40000"
        range: 4K
    XML:
      - "address_table/modules/K_IO.xml"
    UHAL_BASE: 0x81000000
    HDL: "src/CM_IO"    
  
  CM_K_INFO:
    TCL_CALL:
      command:  AXI_PL_DEV_CONNECT
      axi_control: ${::AXI_MASTER_CTRL}
      addr:
        offset: "0x83c43000"
        range:  4K
    XML:
      - "address_table/modules/FW_INFO.xml"
    UHAL_BASE: 0x82000000
    HDL: "src/CM_FW_info"
  
  KINTEX_IPBUS:
    TCL_CALL: 
      command: AXI_PL_DEV_CONNECT
      axi_control: ${::AXI_MASTER_CTRL}
      type: AXI4
      addr:
        offset: "0x8a000000"
        range: 32M
      data_width: "64"
    XML:
      - "address_table/modules/IPBUS.xml"
    UHAL_BASE: 0x85000000    
  
  MPI_KU15P_LEDS:
    TCL_CALL:
      command: AXI_PL_DEV_CONNECT
      axi_control: ${::AXI_MASTER_CTRL}
      addr:
        offset: "0x83c46000"
        range:  4K
    XML:
      - "address_table/modules/MPI_KU15P_LEDS.xml"
    UHAL_BASE: 0x83000000

