#================================================================================
#  Configure and add AXI slaves
#  Auto-generated by 
#================================================================================
#KINTEX_SYS_MGMT
{'axi_control': '${::AXI_MASTER_CTRL}', 'command': 'AXI_IP_SYS_MGMT', 'addr': {'range': '4K', 'offset': '0x83c42000'}, 'enable_i2c_pins': 1, 'remote_slave': '0', 'data_width': '64'}

#KINTEX_IPBUS
{'axi_control': '${::AXI_MASTER_CTRL}', 'type': 'AXI4', 'command': 'AXI_PL_DEV_CONNECT', 'addr': {'range': '32M', 'offset': '0x8A000000'}, 'data_width': '64'}

#CM_K_INFO
{'axi_control': '${::AXI_MASTER_CTRL}', 'command': 'AXI_PL_DEV_CONNECT', 'addr': {'range': '4K', 'offset': '0x83c43000'}, 'data_width': '64'}

#K_C2C_PHY
{'axi_control': '${::AXI_MASTER_CTRL}', 'remote_slave': '0', 'command': 'AXI_DEV_CONNECT', 'addr': {'range': '4K', 'offset': '0x83c44000'}, 'data_width': '64'}

#K_IO
{'axi_control': '${::AXI_MASTER_CTRL}', 'command': 'AXI_PL_DEV_CONNECT', 'addr': {'range': '4K', 'offset': '0x83c40000'}, 'data_width': '64'}

